export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const SET_GAME_RUNNING = 'SET_GAME_RUNNING';
export const SET_GAME_NOT_RUNNING = 'SET_GAME_NOT_RUNNING';
