export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const SET_GAME_RUNNING = 'SET_GAME_RUNNING';

export const ADD_TO_SEQUENCE = 'ADD_TO_SEQUENCE';
export const ADD_TO_PLAYER_SEQUENCE = 'ADD_TO_PLAYER_SEQUENCE';
export const CLEAR_SEQUENCES = 'CLEAR_SEQUENCES';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_PLAYER_TURN = 'SET_PLAYER_TURN';