name: JEST Testing

on:
  pull_request:
    branches-ignore: [ master ]
    
jobs:
  test: 
    name: Run JEST Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Get NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test
  
